wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
batch_size:
  desc: null
  value: 64
L1:
  desc: null
  value: 0.0001
L2:
  desc: null
  value: null
A:
  desc: null
  value: 1
early_patience:
  desc: null
  value: 12
reduce_lr_patience:
  desc: null
  value: 5
architecture:
  desc: null
  value: ECGCNNClassifier
experiment:
  desc: null
  value: pre
use_pretrained:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719722250
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      - 61
      4: 3.12.2
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
