wandb_version: 1

used LDAs:
  desc: null
  value: false
C:
  desc: null
  value: 100
fold:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
architecture:
  desc: null
  value: ECGCNNClassifier_fold8_tachy_B64_L1e-06_24-06-24-11-02.pth
experiment:
  desc: null
  value: tachy
subtype:
  desc: null
  value: 5-class
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722124061
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.12.2
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
