wandb_version: 1

used LDAs:
  desc: null
  value: true
C:
  desc: null
  value: 10
fold:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 64
architecture:
  desc: null
  value: ECGCNNClassifier_fold8_tachy_B64_L2e-06_10-07-24-09-03.pth
experiment:
  desc: null
  value: tachy
ignoreMissing:
  desc: null
  value: false
solver:
  desc: null
  value: svd
subtype:
  desc: null
  value: AVNRT-AVRT+concealed
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722239404
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.2
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
