wandb_version: 1

learning_rate_PTB:
  desc: null
  value: 3.0e-07
learning_rate_BERT:
  desc: null
  value: 1.0e-06
batch_size:
  desc: null
  value: 64
L1:
  desc: null
  value: 0.0001
L2:
  desc: null
  value: 0.0001
A_PTB:
  desc: null
  value: 1
A_BERT:
  desc: null
  value: 1
early_patience:
  desc: null
  value: 12
reduce_lr_patience:
  desc: null
  value: 5
architecture:
  desc: null
  value: ECGCNNClassifier
experiment:
  desc: null
  value: pre
pretrain:
  desc: null
  value: true
finetune:
  desc: null
  value: false
classes_PTB:
  desc: null
  value: 12
use_pretrained:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711367890.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
